package com.application.entity;

import java.util.Date;

public class Book {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_book.id
     *
     * @mbg.generated Wed Aug 28 10:53:52 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_book.title
     *
     * @mbg.generated Wed Aug 28 10:53:52 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_book.cover_url
     *
     * @mbg.generated Wed Aug 28 10:53:52 CST 2019
     */
    private String coverUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_book.author
     *
     * @mbg.generated Wed Aug 28 10:53:52 CST 2019
     */
    private String author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_book.pub_org
     *
     * @mbg.generated Wed Aug 28 10:53:52 CST 2019
     */
    private String pubOrg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_book.pub_date
     *
     * @mbg.generated Wed Aug 28 10:53:52 CST 2019
     */
    private String pubDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_book.isbn
     *
     * @mbg.generated Wed Aug 28 10:53:52 CST 2019
     */
    private String isbn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_book.douban_index
     *
     * @mbg.generated Wed Aug 28 10:53:52 CST 2019
     */
    private Long doubanIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_book.create_time
     *
     * @mbg.generated Wed Aug 28 10:53:52 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_book.update_time
     *
     * @mbg.generated Wed Aug 28 10:53:52 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_book.id
     *
     * @return the value of tbl_book.id
     *
     * @mbg.generated Wed Aug 28 10:53:52 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_book.id
     *
     * @param id the value for tbl_book.id
     *
     * @mbg.generated Wed Aug 28 10:53:52 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_book.title
     *
     * @return the value of tbl_book.title
     *
     * @mbg.generated Wed Aug 28 10:53:52 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_book.title
     *
     * @param title the value for tbl_book.title
     *
     * @mbg.generated Wed Aug 28 10:53:52 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_book.cover_url
     *
     * @return the value of tbl_book.cover_url
     *
     * @mbg.generated Wed Aug 28 10:53:52 CST 2019
     */
    public String getCoverUrl() {
        return coverUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_book.cover_url
     *
     * @param coverUrl the value for tbl_book.cover_url
     *
     * @mbg.generated Wed Aug 28 10:53:52 CST 2019
     */
    public void setCoverUrl(String coverUrl) {
        this.coverUrl = coverUrl == null ? null : coverUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_book.author
     *
     * @return the value of tbl_book.author
     *
     * @mbg.generated Wed Aug 28 10:53:52 CST 2019
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_book.author
     *
     * @param author the value for tbl_book.author
     *
     * @mbg.generated Wed Aug 28 10:53:52 CST 2019
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_book.pub_org
     *
     * @return the value of tbl_book.pub_org
     *
     * @mbg.generated Wed Aug 28 10:53:52 CST 2019
     */
    public String getPubOrg() {
        return pubOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_book.pub_org
     *
     * @param pubOrg the value for tbl_book.pub_org
     *
     * @mbg.generated Wed Aug 28 10:53:52 CST 2019
     */
    public void setPubOrg(String pubOrg) {
        this.pubOrg = pubOrg == null ? null : pubOrg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_book.pub_date
     *
     * @return the value of tbl_book.pub_date
     *
     * @mbg.generated Wed Aug 28 10:53:52 CST 2019
     */
    public String getPubDate() {
        return pubDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_book.pub_date
     *
     * @param pubDate the value for tbl_book.pub_date
     *
     * @mbg.generated Wed Aug 28 10:53:52 CST 2019
     */
    public void setPubDate(String pubDate) {
        this.pubDate = pubDate == null ? null : pubDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_book.isbn
     *
     * @return the value of tbl_book.isbn
     *
     * @mbg.generated Wed Aug 28 10:53:52 CST 2019
     */
    public String getIsbn() {
        return isbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_book.isbn
     *
     * @param isbn the value for tbl_book.isbn
     *
     * @mbg.generated Wed Aug 28 10:53:52 CST 2019
     */
    public void setIsbn(String isbn) {
        this.isbn = isbn == null ? null : isbn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_book.douban_index
     *
     * @return the value of tbl_book.douban_index
     *
     * @mbg.generated Wed Aug 28 10:53:52 CST 2019
     */
    public Long getDoubanIndex() {
        return doubanIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_book.douban_index
     *
     * @param doubanIndex the value for tbl_book.douban_index
     *
     * @mbg.generated Wed Aug 28 10:53:52 CST 2019
     */
    public void setDoubanIndex(Long doubanIndex) {
        this.doubanIndex = doubanIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_book.create_time
     *
     * @return the value of tbl_book.create_time
     *
     * @mbg.generated Wed Aug 28 10:53:52 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_book.create_time
     *
     * @param createTime the value for tbl_book.create_time
     *
     * @mbg.generated Wed Aug 28 10:53:52 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_book.update_time
     *
     * @return the value of tbl_book.update_time
     *
     * @mbg.generated Wed Aug 28 10:53:52 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_book.update_time
     *
     * @param updateTime the value for tbl_book.update_time
     *
     * @mbg.generated Wed Aug 28 10:53:52 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

	@Override
	public String toString() {
		return "Book [id=" + id + ", title=" + title + ", coverUrl=" + coverUrl
				+ ", author=" + author + ", pubOrg=" + pubOrg + ", pubDate="
				+ pubDate + ", isbn=" + isbn + ", doubanIndex=" + doubanIndex
				+ ", createTime=" + createTime + ", updateTime=" + updateTime
				+ "]";
	}
    
}