package com.application.entity;

import java.util.Date;

public class BookFromTag {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_from_tag.id
     *
     * @mbg.generated Sat Aug 24 20:37:00 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_from_tag.title
     *
     * @mbg.generated Sat Aug 24 20:37:00 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_from_tag.cover_url
     *
     * @mbg.generated Sat Aug 24 20:37:00 CST 2019
     */
    private String coverUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_from_tag.author
     *
     * @mbg.generated Sat Aug 24 20:37:00 CST 2019
     */
    private String author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_from_tag.pub_org
     *
     * @mbg.generated Sat Aug 24 20:37:00 CST 2019
     */
    private String pubOrg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_from_tag.pub_date
     *
     * @mbg.generated Sat Aug 24 20:37:00 CST 2019
     */
    private String pubDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_from_tag.douban_index
     *
     * @mbg.generated Sat Aug 24 20:37:00 CST 2019
     */
    private Long doubanIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_from_tag.create_time
     *
     * @mbg.generated Sat Aug 24 20:37:00 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_from_tag.update_time
     *
     * @mbg.generated Sat Aug 24 20:37:00 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_from_tag.id
     *
     * @return the value of book_from_tag.id
     *
     * @mbg.generated Sat Aug 24 20:37:00 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_from_tag.id
     *
     * @param id the value for book_from_tag.id
     *
     * @mbg.generated Sat Aug 24 20:37:00 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_from_tag.title
     *
     * @return the value of book_from_tag.title
     *
     * @mbg.generated Sat Aug 24 20:37:00 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_from_tag.title
     *
     * @param title the value for book_from_tag.title
     *
     * @mbg.generated Sat Aug 24 20:37:00 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_from_tag.cover_url
     *
     * @return the value of book_from_tag.cover_url
     *
     * @mbg.generated Sat Aug 24 20:37:00 CST 2019
     */
    public String getCoverUrl() {
        return coverUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_from_tag.cover_url
     *
     * @param coverUrl the value for book_from_tag.cover_url
     *
     * @mbg.generated Sat Aug 24 20:37:00 CST 2019
     */
    public void setCoverUrl(String coverUrl) {
        this.coverUrl = coverUrl == null ? null : coverUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_from_tag.author
     *
     * @return the value of book_from_tag.author
     *
     * @mbg.generated Sat Aug 24 20:37:00 CST 2019
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_from_tag.author
     *
     * @param author the value for book_from_tag.author
     *
     * @mbg.generated Sat Aug 24 20:37:00 CST 2019
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_from_tag.pub_org
     *
     * @return the value of book_from_tag.pub_org
     *
     * @mbg.generated Sat Aug 24 20:37:00 CST 2019
     */
    public String getPubOrg() {
        return pubOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_from_tag.pub_org
     *
     * @param pubOrg the value for book_from_tag.pub_org
     *
     * @mbg.generated Sat Aug 24 20:37:00 CST 2019
     */
    public void setPubOrg(String pubOrg) {
        this.pubOrg = pubOrg == null ? null : pubOrg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_from_tag.pub_date
     *
     * @return the value of book_from_tag.pub_date
     *
     * @mbg.generated Sat Aug 24 20:37:00 CST 2019
     */
    public String getPubDate() {
        return pubDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_from_tag.pub_date
     *
     * @param pubDate the value for book_from_tag.pub_date
     *
     * @mbg.generated Sat Aug 24 20:37:00 CST 2019
     */
    public void setPubDate(String pubDate) {
        this.pubDate = pubDate == null ? null : pubDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_from_tag.douban_index
     *
     * @return the value of book_from_tag.douban_index
     *
     * @mbg.generated Sat Aug 24 20:37:00 CST 2019
     */
    public Long getDoubanIndex() {
        return doubanIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_from_tag.douban_index
     *
     * @param doubanIndex the value for book_from_tag.douban_index
     *
     * @mbg.generated Sat Aug 24 20:37:00 CST 2019
     */
    public void setDoubanIndex(Long doubanIndex) {
        this.doubanIndex = doubanIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_from_tag.create_time
     *
     * @return the value of book_from_tag.create_time
     *
     * @mbg.generated Sat Aug 24 20:37:00 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_from_tag.create_time
     *
     * @param createTime the value for book_from_tag.create_time
     *
     * @mbg.generated Sat Aug 24 20:37:00 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_from_tag.update_time
     *
     * @return the value of book_from_tag.update_time
     *
     * @mbg.generated Sat Aug 24 20:37:00 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_from_tag.update_time
     *
     * @param updateTime the value for book_from_tag.update_time
     *
     * @mbg.generated Sat Aug 24 20:37:00 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}