package com.application.entity;

public class Link {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link.id
     *
     * @mbg.generated Wed Aug 21 19:22:48 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link.title
     *
     * @mbg.generated Wed Aug 21 19:22:48 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link.link
     *
     * @mbg.generated Wed Aug 21 19:22:48 CST 2019
     */
    private String link;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link.flag
     *
     * @mbg.generated Wed Aug 21 19:22:48 CST 2019
     */
    private Integer flag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link.id
     *
     * @return the value of link.id
     *
     * @mbg.generated Wed Aug 21 19:22:48 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link.id
     *
     * @param id the value for link.id
     *
     * @mbg.generated Wed Aug 21 19:22:48 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link.title
     *
     * @return the value of link.title
     *
     * @mbg.generated Wed Aug 21 19:22:48 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link.title
     *
     * @param title the value for link.title
     *
     * @mbg.generated Wed Aug 21 19:22:48 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link.link
     *
     * @return the value of link.link
     *
     * @mbg.generated Wed Aug 21 19:22:48 CST 2019
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link.link
     *
     * @param link the value for link.link
     *
     * @mbg.generated Wed Aug 21 19:22:48 CST 2019
     */
    public void setLink(String link) {
        this.link = link == null ? null : link.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link.flag
     *
     * @return the value of link.flag
     *
     * @mbg.generated Wed Aug 21 19:22:48 CST 2019
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link.flag
     *
     * @param flag the value for link.flag
     *
     * @mbg.generated Wed Aug 21 19:22:48 CST 2019
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }
}