package com.application.entity;

import java.util.Date;

public class Movie {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_movie.id
     *
     * @mbg.generated Tue Sep 03 15:04:02 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_movie.title
     *
     * @mbg.generated Tue Sep 03 15:04:02 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_movie.year
     *
     * @mbg.generated Tue Sep 03 15:04:02 CST 2019
     */
    private String year;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_movie.cover_url
     *
     * @mbg.generated Tue Sep 03 15:04:02 CST 2019
     */
    private String coverUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_movie.director
     *
     * @mbg.generated Tue Sep 03 15:04:02 CST 2019
     */
    private String director;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_movie.actor
     *
     * @mbg.generated Tue Sep 03 15:04:02 CST 2019
     */
    private String actor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_movie.movie_type
     *
     * @mbg.generated Tue Sep 03 15:04:02 CST 2019
     */
    private String movieType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_movie.conuntry
     *
     * @mbg.generated Tue Sep 03 15:04:02 CST 2019
     */
    private String conuntry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_movie.douban_index
     *
     * @mbg.generated Tue Sep 03 15:04:02 CST 2019
     */
    private Long doubanIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_movie.create_time
     *
     * @mbg.generated Tue Sep 03 15:04:02 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_movie.update_time
     *
     * @mbg.generated Tue Sep 03 15:04:02 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_movie.id
     *
     * @return the value of tbl_movie.id
     *
     * @mbg.generated Tue Sep 03 15:04:02 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_movie.id
     *
     * @param id the value for tbl_movie.id
     *
     * @mbg.generated Tue Sep 03 15:04:02 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_movie.title
     *
     * @return the value of tbl_movie.title
     *
     * @mbg.generated Tue Sep 03 15:04:02 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_movie.title
     *
     * @param title the value for tbl_movie.title
     *
     * @mbg.generated Tue Sep 03 15:04:02 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_movie.year
     *
     * @return the value of tbl_movie.year
     *
     * @mbg.generated Tue Sep 03 15:04:02 CST 2019
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_movie.year
     *
     * @param year the value for tbl_movie.year
     *
     * @mbg.generated Tue Sep 03 15:04:02 CST 2019
     */
    public void setYear(String year) {
        this.year = year == null ? null : year.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_movie.cover_url
     *
     * @return the value of tbl_movie.cover_url
     *
     * @mbg.generated Tue Sep 03 15:04:02 CST 2019
     */
    public String getCoverUrl() {
        return coverUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_movie.cover_url
     *
     * @param coverUrl the value for tbl_movie.cover_url
     *
     * @mbg.generated Tue Sep 03 15:04:02 CST 2019
     */
    public void setCoverUrl(String coverUrl) {
        this.coverUrl = coverUrl == null ? null : coverUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_movie.director
     *
     * @return the value of tbl_movie.director
     *
     * @mbg.generated Tue Sep 03 15:04:02 CST 2019
     */
    public String getDirector() {
        return director;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_movie.director
     *
     * @param director the value for tbl_movie.director
     *
     * @mbg.generated Tue Sep 03 15:04:02 CST 2019
     */
    public void setDirector(String director) {
        this.director = director == null ? null : director.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_movie.actor
     *
     * @return the value of tbl_movie.actor
     *
     * @mbg.generated Tue Sep 03 15:04:02 CST 2019
     */
    public String getActor() {
        return actor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_movie.actor
     *
     * @param actor the value for tbl_movie.actor
     *
     * @mbg.generated Tue Sep 03 15:04:02 CST 2019
     */
    public void setActor(String actor) {
        this.actor = actor == null ? null : actor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_movie.movie_type
     *
     * @return the value of tbl_movie.movie_type
     *
     * @mbg.generated Tue Sep 03 15:04:02 CST 2019
     */
    public String getMovieType() {
        return movieType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_movie.movie_type
     *
     * @param movieType the value for tbl_movie.movie_type
     *
     * @mbg.generated Tue Sep 03 15:04:02 CST 2019
     */
    public void setMovieType(String movieType) {
        this.movieType = movieType == null ? null : movieType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_movie.conuntry
     *
     * @return the value of tbl_movie.conuntry
     *
     * @mbg.generated Tue Sep 03 15:04:02 CST 2019
     */
    public String getConuntry() {
        return conuntry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_movie.conuntry
     *
     * @param conuntry the value for tbl_movie.conuntry
     *
     * @mbg.generated Tue Sep 03 15:04:02 CST 2019
     */
    public void setConuntry(String conuntry) {
        this.conuntry = conuntry == null ? null : conuntry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_movie.douban_index
     *
     * @return the value of tbl_movie.douban_index
     *
     * @mbg.generated Tue Sep 03 15:04:02 CST 2019
     */
    public Long getDoubanIndex() {
        return doubanIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_movie.douban_index
     *
     * @param doubanIndex the value for tbl_movie.douban_index
     *
     * @mbg.generated Tue Sep 03 15:04:02 CST 2019
     */
    public void setDoubanIndex(Long doubanIndex) {
        this.doubanIndex = doubanIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_movie.create_time
     *
     * @return the value of tbl_movie.create_time
     *
     * @mbg.generated Tue Sep 03 15:04:02 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_movie.create_time
     *
     * @param createTime the value for tbl_movie.create_time
     *
     * @mbg.generated Tue Sep 03 15:04:02 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_movie.update_time
     *
     * @return the value of tbl_movie.update_time
     *
     * @mbg.generated Tue Sep 03 15:04:02 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_movie.update_time
     *
     * @param updateTime the value for tbl_movie.update_time
     *
     * @mbg.generated Tue Sep 03 15:04:02 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

	@Override
	public String toString() {
		return "Movie [id=" + id + ", title=" + title + ", year=" + year
				+ ", coverUrl=" + coverUrl + ", director=" + director
				+ ", actor=" + actor + ", movieType=" + movieType
				+ ", conuntry=" + conuntry + ", doubanIndex=" + doubanIndex
				+ ", createTime=" + createTime + ", updateTime=" + updateTime
				+ "]";
	}
}