package com.application.mapper;

import com.application.entity.BookFromTag;
import com.application.entity.BookFromTagExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BookFromTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_from_tag
     *
     * @mbg.generated Sat Aug 24 20:37:00 CST 2019
     */
    long countByExample(BookFromTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_from_tag
     *
     * @mbg.generated Sat Aug 24 20:37:00 CST 2019
     */
    int deleteByExample(BookFromTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_from_tag
     *
     * @mbg.generated Sat Aug 24 20:37:00 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_from_tag
     *
     * @mbg.generated Sat Aug 24 20:37:00 CST 2019
     */
    int insert(BookFromTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_from_tag
     *
     * @mbg.generated Sat Aug 24 20:37:00 CST 2019
     */
    int insertSelective(BookFromTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_from_tag
     *
     * @mbg.generated Sat Aug 24 20:37:00 CST 2019
     */
    List<BookFromTag> selectByExample(BookFromTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_from_tag
     *
     * @mbg.generated Sat Aug 24 20:37:00 CST 2019
     */
    BookFromTag selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_from_tag
     *
     * @mbg.generated Sat Aug 24 20:37:00 CST 2019
     */
    int updateByExampleSelective(@Param("record") BookFromTag record, @Param("example") BookFromTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_from_tag
     *
     * @mbg.generated Sat Aug 24 20:37:00 CST 2019
     */
    int updateByExample(@Param("record") BookFromTag record, @Param("example") BookFromTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_from_tag
     *
     * @mbg.generated Sat Aug 24 20:37:00 CST 2019
     */
    int updateByPrimaryKeySelective(BookFromTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_from_tag
     *
     * @mbg.generated Sat Aug 24 20:37:00 CST 2019
     */
    int updateByPrimaryKey(BookFromTag record);
}