package com.application.mapper;

import com.application.entity.BookTag;
import com.application.entity.BookTagExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BookTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_tag
     *
     * @mbg.generated Mon Aug 19 14:04:13 CST 2019
     */
    long countByExample(BookTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_tag
     *
     * @mbg.generated Mon Aug 19 14:04:13 CST 2019
     */
    int deleteByExample(BookTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_tag
     *
     * @mbg.generated Mon Aug 19 14:04:13 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_tag
     *
     * @mbg.generated Mon Aug 19 14:04:13 CST 2019
     */
    int insert(BookTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_tag
     *
     * @mbg.generated Mon Aug 19 14:04:13 CST 2019
     */
    int insertSelective(BookTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_tag
     *
     * @mbg.generated Mon Aug 19 14:04:13 CST 2019
     */
    List<BookTag> selectByExample(BookTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_tag
     *
     * @mbg.generated Mon Aug 19 14:04:13 CST 2019
     */
    BookTag selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_tag
     *
     * @mbg.generated Mon Aug 19 14:04:13 CST 2019
     */
    int updateByExampleSelective(@Param("record") BookTag record, @Param("example") BookTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_tag
     *
     * @mbg.generated Mon Aug 19 14:04:13 CST 2019
     */
    int updateByExample(@Param("record") BookTag record, @Param("example") BookTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_tag
     *
     * @mbg.generated Mon Aug 19 14:04:13 CST 2019
     */
    int updateByPrimaryKeySelective(BookTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_tag
     *
     * @mbg.generated Mon Aug 19 14:04:13 CST 2019
     */
    int updateByPrimaryKey(BookTag record);
}