package com.application.mapper;

import com.application.entity.Link;
import com.application.entity.LinkExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LinkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link
     *
     * @mbg.generated Wed Aug 21 19:22:48 CST 2019
     */
    long countByExample(LinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link
     *
     * @mbg.generated Wed Aug 21 19:22:48 CST 2019
     */
    int deleteByExample(LinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link
     *
     * @mbg.generated Wed Aug 21 19:22:48 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link
     *
     * @mbg.generated Wed Aug 21 19:22:48 CST 2019
     */
    int insert(Link record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link
     *
     * @mbg.generated Wed Aug 21 19:22:48 CST 2019
     */
    int insertSelective(Link record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link
     *
     * @mbg.generated Wed Aug 21 19:22:48 CST 2019
     */
    List<Link> selectByExample(LinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link
     *
     * @mbg.generated Wed Aug 21 19:22:48 CST 2019
     */
    Link selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link
     *
     * @mbg.generated Wed Aug 21 19:22:48 CST 2019
     */
    int updateByExampleSelective(@Param("record") Link record, @Param("example") LinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link
     *
     * @mbg.generated Wed Aug 21 19:22:48 CST 2019
     */
    int updateByExample(@Param("record") Link record, @Param("example") LinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link
     *
     * @mbg.generated Wed Aug 21 19:22:48 CST 2019
     */
    int updateByPrimaryKeySelective(Link record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link
     *
     * @mbg.generated Wed Aug 21 19:22:48 CST 2019
     */
    int updateByPrimaryKey(Link record);
}